export const ACTIONS = {
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  CACHE_FETCH_SUCCESS: 'CACHE_FETCH_SUCCESS',
  SELECT_MATCH: 'SELECT_MATCH',
  ADD_MATCH: 'ADD_MATCH',
  UPDATE_MATCH: 'UPDATE_MATCH',
  REMOVE_MATCH: 'REMOVE_MATCH',
  CLEAR_MATCHES: 'CLEAR_MATCHES',
  RESET_MATCHES: 'RESET_MATCHES',
  UPDATE_MATCHES: 'UPDATE_MATCHES',
  CHANGE_SPORT: 'CHANGE_SPORT',
};
